name: CommandLogGuardian
api: 5.0.0
version: 1.0.1
main: nicholass003\commandlogguardian\CommandLogGuardian
author: nicholass003
src-namespace-prefix: nicholass003\commandlogguardian
commands:
  commandlogguardian:
    description: CommandLogGuardian Commands
    permission: commandlogguardian.command
    aliases:
    - clg
    - commandlog
    - commandguardian
permissions:
  commandlogguardian.command:
    default: op